// <auto-generated />
using System;
using Maiven_Portal_Managment.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Maiven_Portal_Managment.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260923155732_AddFaceCredentials")]
    partial class AddFaceCredentials
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Maiven_Portal_Managment.Data.Entities.AcademicYear", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("isDelete");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_ACADEMIC_YEARS_name_not_deleted")
                        .HasFilter("[isDelete] = 0");

                    b.HasIndex("Status")
                        .IsUnique()
                        .HasDatabaseName("UX_ACADEMIC_YEARS_active_not_deleted")
                        .HasFilter("[isDelete] = 0 AND [status] = 'ACTIVE'");

                    b.HasIndex("IsDeleted", "Status")
                        .HasDatabaseName("IX_ACADEMIC_YEARS_isDelete_status");

                    b.ToTable("ACADEMIC_YEARS", null, t =>
                        {
                            t.HasCheckConstraint("CK_ACADEMIC_YEARS_date_range", "[start_date] <= [end_date]");

                            t.HasCheckConstraint("CK_ACADEMIC_YEARS_status", "[status] IN ('ACTIVE', 'COMPLETED')");
                        });
                });

            modelBuilder.Entity("Maiven_Portal_Managment.Data.Entities.Announcement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("isDelete");

                    b.Property<long?>("SectionId")
                        .HasColumnType("bigint")
                        .HasColumnName("section_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("IX_ANNOUNCEMENTS_created_by");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_ANNOUNCEMENTS_isDelete");

                    b.HasIndex("SectionId")
                        .HasDatabaseName("IX_ANNOUNCEMENTS_section_id");

                    b.ToTable("ANNOUNCEMENTS", (string)null);
                });

            modelBuilder.Entity("Maiven_Portal_Managment.Data.Entities.Course", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("course_code");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("course_name");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("Credits")
                        .HasColumnType("int")
                        .HasColumnName("credits");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("isDelete");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id");

                    b.HasIndex("CourseCode")
                        .IsUnique()
                        .HasDatabaseName("UX_COURSES_course_code");

                    b.HasIndex("IsDeleted", "Status")
                        .HasDatabaseName("IX_COURSES_isDelete_status");

                    b.ToTable("COURSES", null, t =>
                        {
                            t.HasCheckConstraint("CK_COURSES_credits", "[credits] >= 0");

                            t.HasCheckConstraint("CK_COURSES_status", "[status] IN ('ACTIVE', 'INACTIVE')");
                        });
                });

            modelBuilder.Entity("Maiven_Portal_Managment.Data.Entities.CourseResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<long>("EnrollmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("enrollment_id");

                    b.Property<decimal?>("FinalScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("final_score");

                    b.Property<decimal?>("GradePoint")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("grade_point");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("isDelete");

                    b.Property<string>("LetterGrade")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("letter_grade");

                    b.Property<string>("ResultStatus")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("result_status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id");

                    b.HasIndex("EnrollmentId")
                        .IsUnique()
                        .HasDatabaseName("UX_COURSE_RESULTS_enrollment_id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_COURSE_RESULTS_isDelete");

                    b.ToTable("COURSE_RESULTS", null, t =>
                        {
                            t.HasCheckConstraint("CK_COURSE_RESULTS_final_score", "[final_score] >= 0 AND [final_score] <= 100");

                            t.HasCheckConstraint("CK_COURSE_RESULTS_grade_point", "[grade_point] >= 0");

                            t.HasCheckConstraint("CK_COURSE_RESULTS_result_status", "[result_status] IN ('PASS', 'FAIL', 'INCOMPLETE')");
                        });
                });

            modelBuilder.Entity("Maiven_Portal_Managment.Data.Entities.CourseSection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("capacity");

                    b.Property<long>("CourseId")
                        .HasColumnType("bigint")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("day_of_week");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<int>("EndPeriod")
                        .HasColumnType("int")
                        .HasColumnName("end_period");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("isDelete");

                    b.Property<string>("SectionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("section_code");

                    b.Property<long>("SemesterId")
                        .HasColumnType("bigint")
                        .HasColumnName("semester_id");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<int>("StartPeriod")
                        .HasColumnType("int")
                        .HasColumnName("start_period");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("status");

                    b.Property<long>("TeacherUserRoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("teacher_user_role_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("IX_COURSE_SECTIONS_course_id");

                    b.HasIndex("TeacherUserRoleId")
                        .HasDatabaseName("IX_COURSE_SECTIONS_teacher_user_role_id");

                    b.HasIndex("IsDeleted", "Status")
                        .HasDatabaseName("IX_COURSE_SECTIONS_isDelete_status");

                    b.HasIndex("SemesterId", "SectionCode")
                        .IsUnique()
                        .HasDatabaseName("UX_COURSE_SECTIONS_semester_id_section_code");

                    b.ToTable("COURSE_SECTIONS", null, t =>
                        {
                            t.HasCheckConstraint("CK_COURSE_SECTIONS_capacity", "[capacity] >= 0");

                            t.HasCheckConstraint("CK_COURSE_SECTIONS_date_range", "[start_date] <= [end_date]");

                            t.HasCheckConstraint("CK_COURSE_SECTIONS_day_of_week", "[day_of_week] IN ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY')");

                            t.HasCheckConstraint("CK_COURSE_SECTIONS_end_period", "[end_period] BETWEEN 1 AND 10");

                            t.HasCheckConstraint("CK_COURSE_SECTIONS_period_range", "[start_period] < [end_period]");

                            t.HasCheckConstraint("CK_COURSE_SECTIONS_start_period", "[start_period] BETWEEN 1 AND 10");

                            t.HasCheckConstraint("CK_COURSE_SECTIONS_status", "[status] IN ('OPEN', 'COMPLETED', 'CANCELLED')");
                        });
                });

            modelBuilder.Entity("Maiven_Portal_Managment.Data.Entities.Enrollment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("isDelete");

                    b.Property<long>("SectionId")
                        .HasColumnType("bigint")
                        .HasColumnName("section_id");

                    b.Property<long>("StudentUserRoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("student_user_role_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_ENROLLMENTS_isDelete");

                    b.HasIndex("SectionId")
                        .HasDatabaseName("IX_ENROLLMENTS_section_id");

                    b.HasIndex("StudentUserRoleId", "SectionId")
                        .IsUnique()
                        .HasDatabaseName("UX_ENROLLMENTS_student_user_role_id_section_id");

                    b.ToTable("ENROLLMENTS", (string)null);
                });

            modelBuilder.Entity("Maiven_Portal_Managment.Data.Entities.FaceCredential", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<byte[]>("Embedding")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("embedding");

                    b.Property<int>("EmbeddingDimension")
                        .HasColumnType("int")
                        .HasColumnName("embedding_dimension");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("isDelete");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("model_name");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("model_version");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_FACE_CREDENTIALS_isDelete");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("UX_FACE_CREDENTIALS_user_id_active")
                        .HasFilter("[isDelete] = 0");

                    b.ToTable("FACE_CREDENTIALS", null, t =>
                        {
                            t.HasCheckConstraint("CK_FACE_CREDENTIALS_delete_state", "([isDelete] = 0 AND [embedding] IS NOT NULL AND [deleted_at] IS NULL) OR ([isDelete] = 1 AND [embedding] IS NULL AND [deleted_at] IS NOT NULL)");

                            t.HasCheckConstraint("CK_FACE_CREDENTIALS_embedding_dimension", "[embedding_dimension] > 0");

                            t.HasCheckConstraint("CK_FACE_CREDENTIALS_embedding_length", "[embedding] IS NULL OR DATALENGTH([embedding]) = [embedding_dimension] * 4");
                        });
                });

            modelBuilder.Entity("Maiven_Portal_Managment.Data.Entities.GradeComponent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("isDelete");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<long>("SectionId")
                        .HasColumnType("bigint")
                        .HasColumnName("section_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<decimal>("Weight")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_GRADE_COMPONENTS_isDelete");

                    b.HasIndex("SectionId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UX_GRADE_COMPONENTS_section_id_name");

                    b.ToTable("GRADE_COMPONENTS", null, t =>
                        {
                            t.HasCheckConstraint("CK_GRADE_COMPONENTS_weight", "[weight] >= 0 AND [weight] <= 100");
                        });
                });

            modelBuilder.Entity("Maiven_Portal_Managment.Data.Entities.RegistrationPeriod", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_at");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("isDelete");

                    b.Property<long>("SemesterId")
                        .HasColumnType("bigint")
                        .HasColumnName("semester_id");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("IX_REGISTRATION_PERIODS_created_by");

                    b.HasIndex("SemesterId")
                        .HasDatabaseName("IX_REGISTRATION_PERIODS_semester_id");

                    b.HasIndex("IsDeleted", "Status")
                        .HasDatabaseName("IX_REGISTRATION_PERIODS_isDelete_status");

                    b.ToTable("REGISTRATION_PERIODS", null, t =>
                        {
                            t.HasCheckConstraint("CK_REGISTRATION_PERIODS_date_range", "[start_at] < [end_at]");

                            t.HasCheckConstraint("CK_REGISTRATION_PERIODS_status", "[status] IN ('UPCOMING', 'OPEN', 'CLOSED')");
                        });
                });

            modelBuilder.Entity("Maiven_Portal_Managment.Data.Entities.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("isDelete");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_ROLES_code");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_ROLES_isDelete");

                    b.ToTable("ROLES", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "STUDENT",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Student self-registration role.",
                            IsDeleted = false,
                            Name = "Student",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2L,
                            Code = "TEACHER",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Teacher role.",
                            IsDeleted = false,
                            Name = "Teacher",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3L,
                            Code = "ADMIN",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "System administrator role.",
                            IsDeleted = false,
                            Name = "Admin",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Maiven_Portal_Managment.Data.Entities.Semester", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AcademicYearId")
                        .HasColumnType("bigint")
                        .HasColumnName("academic_year_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("isDelete");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id");

                    b.HasIndex("AcademicYearId")
                        .HasDatabaseName("IX_SEMESTERS_academic_year_id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_SEMESTERS_isDelete");

                    b.ToTable("SEMESTERS", null, t =>
                        {
                            t.HasCheckConstraint("CK_SEMESTERS_date_range", "[start_date] <= [end_date]");
                        });
                });

            modelBuilder.Entity("Maiven_Portal_Managment.Data.Entities.StudentScore", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ComponentId")
                        .HasColumnType("bigint")
                        .HasColumnName("component_id");

                    b.Property<long>("EnrollmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("enrollment_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("isDelete");

                    b.Property<decimal?>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("score");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<long>("UpdatedById")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("ComponentId")
                        .HasDatabaseName("IX_STUDENT_SCORES_component_id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_STUDENT_SCORES_isDelete");

                    b.HasIndex("UpdatedById")
                        .HasDatabaseName("IX_STUDENT_SCORES_updated_by");

                    b.HasIndex("EnrollmentId", "ComponentId")
                        .IsUnique()
                        .HasDatabaseName("UX_STUDENT_SCORES_enrollment_id_component_id");

                    b.ToTable("STUDENT_SCORES", null, t =>
                        {
                            t.HasCheckConstraint("CK_STUDENT_SCORES_score", "[score] >= 0 AND [score] <= 100");
                        });
                });

            modelBuilder.Entity("Maiven_Portal_Managment.Data.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("address");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("gender");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("isDelete");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("phone");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_USERS_email");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_USERS_isDelete");

                    b.ToTable("USERS", null, t =>
                        {
                            t.HasCheckConstraint("CK_USERS_gender", "[gender] IN ('MALE', 'FEMALE', 'OTHER')");
                        });
                });

            modelBuilder.Entity("Maiven_Portal_Managment.Data.Entities.UserRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("isDelete");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_USER_ROLES_isDelete");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("IX_USER_ROLES_role_id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("UX_USER_ROLES_user_id_active")
                        .HasFilter("[isDelete] = 0");

                    b.ToTable("USER_ROLES", (string)null);
                });

            modelBuilder.Entity("Maiven_Portal_Managment.Data.Entities.Announcement", b =>
                {
                    b.HasOne("Maiven_Portal_Managment.Data.Entities.User", "CreatedBy")
                        .WithMany("CreatedAnnouncements")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Maiven_Portal_Managment.Data.Entities.CourseSection", "Section")
                        .WithMany("Announcements")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedBy");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("Maiven_Portal_Managment.Data.Entities.CourseResult", b =>
                {
                    b.HasOne("Maiven_Portal_Managment.Data.Entities.Enrollment", "Enrollment")
                        .WithOne("CourseResult")
                        .HasForeignKey("Maiven_Portal_Managment.Data.Entities.CourseResult", "EnrollmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("Maiven_Portal_Managment.Data.Entities.CourseSection", b =>
                {
                    b.HasOne("Maiven_Portal_Managment.Data.Entities.Course", "Course")
                        .WithMany("CourseSections")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Maiven_Portal_Managment.Data.Entities.Semester", "Semester")
                        .WithMany("CourseSections")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Maiven_Portal_Managment.Data.Entities.UserRole", "TeacherUserRole")
                        .WithMany("TaughtCourseSections")
                        .HasForeignKey("TeacherUserRoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Semester");

                    b.Navigation("TeacherUserRole");
                });

            modelBuilder.Entity("Maiven_Portal_Managment.Data.Entities.Enrollment", b =>
                {
                    b.HasOne("Maiven_Portal_Managment.Data.Entities.CourseSection", "Section")
                        .WithMany("Enrollments")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Maiven_Portal_Managment.Data.Entities.UserRole", "StudentUserRole")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentUserRoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Section");

                    b.Navigation("StudentUserRole");
                });

            modelBuilder.Entity("Maiven_Portal_Managment.Data.Entities.FaceCredential", b =>
                {
                    b.HasOne("Maiven_Portal_Managment.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Maiven_Portal_Managment.Data.Entities.GradeComponent", b =>
                {
                    b.HasOne("Maiven_Portal_Managment.Data.Entities.CourseSection", "Section")
                        .WithMany("GradeComponents")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("Maiven_Portal_Managment.Data.Entities.RegistrationPeriod", b =>
                {
                    b.HasOne("Maiven_Portal_Managment.Data.Entities.User", "CreatedBy")
                        .WithMany("CreatedRegistrationPeriods")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Maiven_Portal_Managment.Data.Entities.Semester", "Semester")
                        .WithMany("RegistrationPeriods")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("Maiven_Portal_Managment.Data.Entities.Semester", b =>
                {
                    b.HasOne("Maiven_Portal_Managment.Data.Entities.AcademicYear", "AcademicYear")
                        .WithMany("Semesters")
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AcademicYear");
                });

            modelBuilder.Entity("Maiven_Portal_Managment.Data.Entities.StudentScore", b =>
                {
                    b.HasOne("Maiven_Portal_Managment.Data.Entities.GradeComponent", "Component")
                        .WithMany("StudentScores")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Maiven_Portal_Managment.Data.Entities.Enrollment", "Enrollment")
                        .WithMany("StudentScores")
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Maiven_Portal_Managment.Data.Entities.User", "UpdatedBy")
                        .WithMany("UpdatedStudentScores")
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("Enrollment");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("Maiven_Portal_Managment.Data.Entities.UserRole", b =>
                {
                    b.HasOne("Maiven_Portal_Managment.Data.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Maiven_Portal_Managment.Data.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Maiven_Portal_Managment.Data.Entities.AcademicYear", b =>
                {
                    b.Navigation("Semesters");
                });

            modelBuilder.Entity("Maiven_Portal_Managment.Data.Entities.Course", b =>
                {
                    b.Navigation("CourseSections");
                });

            modelBuilder.Entity("Maiven_Portal_Managment.Data.Entities.CourseSection", b =>
                {
                    b.Navigation("Announcements");

                    b.Navigation("Enrollments");

                    b.Navigation("GradeComponents");
                });

            modelBuilder.Entity("Maiven_Portal_Managment.Data.Entities.Enrollment", b =>
                {
                    b.Navigation("CourseResult");

                    b.Navigation("StudentScores");
                });

            modelBuilder.Entity("Maiven_Portal_Managment.Data.Entities.GradeComponent", b =>
                {
                    b.Navigation("StudentScores");
                });

            modelBuilder.Entity("Maiven_Portal_Managment.Data.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Maiven_Portal_Managment.Data.Entities.Semester", b =>
                {
                    b.Navigation("CourseSections");

                    b.Navigation("RegistrationPeriods");
                });

            modelBuilder.Entity("Maiven_Portal_Managment.Data.Entities.User", b =>
                {
                    b.Navigation("CreatedAnnouncements");

                    b.Navigation("CreatedRegistrationPeriods");

                    b.Navigation("UpdatedStudentScores");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Maiven_Portal_Managment.Data.Entities.UserRole", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("TaughtCourseSections");
                });
#pragma warning restore 612, 618
        }
    }
}
